Add Surface images
Ultramarine-Linux/build-scripts pull request #48
Opened 2024-10-01 14:01 UTC by nothingneko

2024-10-01 14:49 UTC, nothingneko commented
workaround didn't work

we need to wait for surface kernel to fix 41

2024-10-09 18:20 UTC, nothingneko commented
TODO

[] remove Surface aarch builds
[] wait on upstream to fix F41

2024-10-26 06:44 UTC, Owen-sz commented
https://github.com/Ultramarine-Linux/packages/pull/87

2024-10-27 04:38 UTC, Owen-sz commented
Note (to myself as well):

- surface-dtx-daemon
- ultramarine-release-surface
- ultramarine-release-identity-surface

Probably

2024-10-30 00:25 UTC, Owen-sz requested changes

2024-10-30 00:25 UTC, Owen-sz commented on katsu/modules/ports/surface/surface.yaml
> +    - kernel-surface-devel
```suggestion
    - kernel-surface-devel
    - ultramarine-release-surface
    - surface-dtx-daemon
```

2024-10-30 00:39 UTC, Owen-sz commented
> Note (to myself as well):
> 
>     * surface-dtx-daemon
> 
>     * ultramarine-release-surface
> 
>     * ultramarine-release-identity-surface
> 
> 
> Probably

Shouldn't need identity, good to go now.

2024-10-30 01:32 UTC, june-fish requested changes
You should exclude the standard kernel for images using the surface kernel, look at how this was one for chromebooks for reference.

2024-10-30 01:35 UTC, nothingneko commented
> You should exclude the standard kernel for images using the surface kernel, look at how this was one for chromebooks for reference.

I swear I already did this

2024-10-30 01:36 UTC, Owen-sz submitted a review, later dismissed

2024-10-31 04:10 UTC, Owen-sz submitted a review, later dismissed

2024-10-31 05:45 UTC, madonuko commented on katsu/modules/base/repodir/linux-surface.repo
> +baseurl=https://pkg.surfacelinux.com/fedora/f40/
```suggestion
baseurl=https://pkg.surfacelinux.com/fedora/f41/
```

2024-10-31 19:31 UTC, june-fish approved these changes, later dismissed

2024-11-01 03:06 UTC, madonuko submitted a review, later dismissed

2024-11-09 05:35 UTC, Owen-sz approved these changes, later dismissed

2025-02-06 08:57 UTC, madonuko commented
resolve the merge conflicts

2025-02-16 18:18 UTC, Owen-sz commented
@nothingneko Please edit the readme to say it is an anywhere port, then should be good to merge.

2025-02-16 20:06 UTC, Owen-sz approved these changes, later dismissed

2025-02-16 20:09 UTC, nothingneko commented on katsu/modules/ports/surface/README.MD
> +These are not a new edition, they are simply Ultramarine with the Surface kernel preinstalled.
```suggestion
Ultramarine on Surface is part of Ultramarine Anywhere.
```

2025-02-16 20:09 UTC, Owen-sz approved these changes

2025-02-16 20:10 UTC, merged